#  spring.application.name=bookstore
server:
    port: 8089
    servlet:
      context-path: /bookstore
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/manuel_bookstore
      username: postgres
      password: ${PASSWORD:password}

  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: validate
      show-sql: false
      properties:
          hibernate:
              session:
                  events:
                      log:
                          LOG_QUERIES_SLOWER_THAN_MS: ${SLOW_QUERIES_MS:25}
              format_sql: true
              dialect: org.hibernate.dialect.PostgreSQLDialect
          hibernate.id.new_generator_mappings: true
          hibernate.connection.provider_disables_autocommit: false
          data:
            jpa:
              repositories:
                bootstrap-mode: lazy
          jackson:
            serialization:
              fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    user: 'postgres'
    password: 'password'

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

